name: Run pre-commit hooks
on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.8'

      - name: Install dev requirements
        run: pip install -r dev-requirements.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure

